-- DROP DATABASE IF EXISTS Burgers_DB;

CREATE DATABASE Burgers_DB;

USE Burgers_DB;

CREATE TABLE burgers (
    id INTEGER(10)  AUTO_INCREMENT NOT NULL,
    burger_type VARCHAR(255) NOT NULL,
    devoured BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (id)
);